<template>
  <v-layout align-center justify-center column fill-height>
    <v-flex>
      <transition appear appear-to-class="fold-out">
        <p class="display-3 font-weight-medium">Little Mousey</p>
      </transition>
    </v-flex>
    <v-flex class="text-md-center">
      <h1>{{ greeting }}</h1>
      <p>
        You can find an overview of Little mousey's personal projects and
        travels on this website. <br />
        Enjoy! 🐭
      </p>
    </v-flex>
    <v-flex>
      <img src="/img/haveamiceday.png" alt="Have a mice day" />
    </v-flex>
    <v-flex>
      <p class="title">
        {{ currentWord }}
      </p>
    </v-flex>
  </v-layout>
</template>

<script>
export default {
  name: 'Homepage',
  data() {
    return {
      greeting: 'Welcome',
      translations: [
        'klein muisje',
        'la petite souris',
        '小老鼠',
        'pieni hiiri',
        'kleine Maus',
        '小さなネズミ',
        '작은 마우스'
      ],
      currentWord: ''
    }
  },
  created() {
    this.getTime()
    this.setTranslation()
  },
  methods: {
    getTime() {
      const date = new Date()
      const hour = date.getHours()

      if (hour) {
        this.greeting = this.setGreeting(hour)
      }
    },
    setGreeting(hour) {
      if (hour < 6) {
        return 'Good night 🌙'
      }
      if (hour < 12) {
        return 'Good morning! 🌄'
      }
      if (hour < 18) {
        return 'Good afternoon ☀️'
      } else {
        return 'Good evening 🌃'
      }
    },
    setTranslation() {
      this.currentWord = this.translations[0]
      let position = 1
      setInterval(() => {
        if (position > this.translations.length - 1) {
          position = 0
        }

        this.currentWord = this.translations[position]
        position++
      }, 2000)
    }
  }
}
</script>

<style lang="scss" scoped>
.fold-out {
  -webkit-animation: fold-out 0.8s cubic-bezier(0.215, 0.61, 0.355, 1) both;
  animation: fold-out 0.8s cubic-bezier(0.215, 0.61, 0.355, 1) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2019-7-8 10:26:39
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes fold-out {
  0% {
    letter-spacing: -0.5em;
    -webkit-transform: translateZ(-700px);
    transform: translateZ(-700px);
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
    opacity: 1;
  }
}
@keyframes fold-out {
  0% {
    letter-spacing: -0.5em;
    -webkit-transform: translateZ(-700px);
    transform: translateZ(-700px);
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
    opacity: 1;
  }
}
</style>
